# Generated by Django 4.0.2 on 2022-02-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Urgent'), (2, 'High'), (3, 'Medium'), (4, 'Low')]),
        ),
    ]
